server:
  port: 8099
  context-path: /ledger
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
#    password: ycj123456
    url: jdbc:mysql://localhost:3306/ledger?useSSL=false
  redis:
    host: localhost
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0

logging:
  file: logs/spring-boot-logging.log
  level:
    com:
      ycj:
        ledger:
          mapper: debug

mybatis:
  type-aliases-package: com.ycj.ledger.domain
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
     cache-enabled: true
     mapUnderscoreToCamelCase: true

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql



